

matplotlib_Line2D_valid_keyword_arguments = (
      'agg_filter',
      'alpha',
      'animated',
      'antialiased',
      'aa',
      'axes',
      'clip_box',
      'clip_on',
      'clip_path',
      'color',
      'c',
      'contains',
      'dash_capstyle',
      'dash_joinstyle',
      'dashes',
      'data',
      'drawstyle',
      'figure',
      'fillstyle',
      'gid',
      'label',
      'linestyle',
      'ls',
      'linewidth',
      'lw',
      'lod',
      'marker',
      'markeredgecolor',
      'mec',
      'markeredgewidth',
      'mew',
      'markerfacecolor',
      'mfc',
      'markerfacecoloralt ',
      'mfcalt',
      'markersize',
      'ms',
      'markevery',
      'picker',
      'pickradius',
      'rasterized',
      'snap',
      'solid_capstyle',
      'solid_joinstyle',
      'transform',
      'url',
      'visible',
      'xdata',
      'ydata',
      'zorder',
    )

