import matplotlib

from feynman import Diagram

fig = matplotlib.pyplot.figure(figsize=(1.,1.))
ax = fig.add_axes([0,0,10,10], frameon=False)
diagram = Diagram(ax)
#diagram.text(.5,0.9,"Vector Boson Fusion (VBF)",fontsize=40)
in1 = diagram.vertex(xy=(.1,.8), marker='')
in2= diagram.vertex(xy=(.1,.2), marker='')
v1 = diagram.vertex(xy=(.4,.7))
v2 = diagram.vertex(xy=(.4,.3))
v3 = diagram.vertex(xy=(.4,.5))
out1 = diagram.vertex(xy=(.9,.8), marker='')
out2 = diagram.vertex(xy=(.9,.2), marker='')
higgsout = diagram.vertex(xy=(.65,.5))
wout1 = diagram.vertex(xy=(.9,.7), marker='')
wout2 = diagram.vertex(xy=(.9,.3), marker='')

q1 = diagram.line(in1, v1, arrow=False)
q2 = diagram.line(in2, v2, arrow=False)
wz1 = diagram.line(v1, v3, style='wiggly')
wz2 = diagram.line(v2, v3, style='wiggly')
w1 = diagram.line(higgsout, wout1, style='wiggly',arrow=False)
w2 = diagram.line(wout2, higgsout, style='wiggly',arrow=False)
higgs = diagram.line(v3, higgsout, style='dashed', arrow=False)
q3 = diagram.line(v1, out1, arrow=False)
q4 = diagram.line(v2, out2, arrow=False)

q1.text("$q_1$",fontsize=30)
q2.text("$q_2$",fontsize=30)
diagram.text(v3.xy[0]+.1, v3.xy[1]+.1, "$Z/W^\pm$",fontsize=30)
diagram.text(v3.xy[0]+.1, v3.xy[1]-.12, "$Z/W^\pm$",fontsize=30)
q3.text("$q_3$",fontsize=30)
q4.text("$q_4$",fontsize=30)
higgs.text("$H/A$",fontsize=30)
diagram.text(wout1.xy[0]+.025,wout1.xy[1],"$W$",fontsize=30)
diagram.text(wout2.xy[0]+.025,wout2.xy[1],"$W$",fontsize=30)
diagram.text(higgsout.xy[0]+0.23,higgsout.xy[1]-0.01,"$\kappa_\mathrm{SM}/\kappa_{AWW}/\kappa_{HWW}$",fontsize=35)
diagram.text(v3.xy[0]-0.17,v3.xy[1]+0.04,"$\kappa_\mathrm{SM}/$",fontsize=35)
diagram.text(v3.xy[0]-0.17,v3.xy[1],"$\kappa_{AWW}/\kappa_{AZZ}/$",fontsize=35)
diagram.text(v3.xy[0]-0.17,v3.xy[1]-0.04,"$\kappa_{HWW}/\kappa_{HZZ}$",fontsize=35)
diagram.plot()
fig.savefig('pdf/VBFHWW-EFT.pdf',bbox_inches='tight')
